language: objective-c

script:
  xctool -project ZLSwipeableViewDemo/ZLSwipeableViewDemo.xcodeproj -scheme ZLSwipeableViewDemo -sdk iphonesimulator build test
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
osx_image: xcode7.3
